version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true #docker-compose only used for development
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"


  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
