"""URL mappings for the recipe app"""

from django.urls import include, path
from recipe import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
# recipe viewset will have auto generated urls depending on the methods
router.register("recipes", views.RecipeViewSet)

# for reverse lookups
app_name = "recipe"

# include urls generated by the router
urlpatterns = [path("", include(router.urls))]
